package schema

import (
	"bytes"
	"fmt"
	"strings"
)

// SDKLanguage defines supported export targets for SDK generation.
type SDKLanguage string

const (
	SDKTypeScript SDKLanguage = "typescript"
	SDKGo         SDKLanguage = "go"
	SDKPython     SDKLanguage = "python"
	SDKCurl       SDKLanguage = "curl"
)

// GenerateClientSDK generates a self-contained, typed client SDK from an OpenAPI spec.
func GenerateClientSDK(spec map[string]any, lang SDKLanguage, baseURL string) (string, string, error) {
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}

	title := "ApiClient"
	if info, ok := spec["info"].(map[string]any); ok {
		if t, ok := info["title"].(string); ok && t != "" {
			title = sanitizeIdentifier(t)
		}
	}

	switch lang {
	case SDKTypeScript:
		return generateTypeScriptSDK(spec, title, baseURL)
	case SDKGo:
		return generateGoSDK(spec, title, baseURL)
	case SDKPython:
		return generatePythonSDK(spec, title, baseURL)
	default:
		return generateTypeScriptSDK(spec, title, baseURL)
	}
}

func sanitizeIdentifier(s string) string {
	var b strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') {
			b.WriteRune(ch)
		}
	}
	res := b.String()
	if res == "" {
		return "ApiClient"
	}
	return res
}

func generateTypeScriptSDK(spec map[string]any, title, baseURL string) (string, string, error) {
	var buf bytes.Buffer
	buf.WriteString("/**\n")
	buf.WriteString(fmt.Sprintf(" * Auto-generated TypeScript Client SDK for %s\n", title))
	buf.WriteString(" * Generated by go-apidocs Client SDK Engine\n")
	buf.WriteString(" */\n\n")

	buf.WriteString("export interface ClientOptions {\n")
	buf.WriteString("  baseUrl?: string;\n")
	buf.WriteString("  accessToken?: string;\n")
	buf.WriteString("  tenantId?: string;\n")
	buf.WriteString("  customHeaders?: Record<string, string>;\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("export class %s {\n", title))
	buf.WriteString("  private baseUrl: string;\n")
	buf.WriteString("  private accessToken?: string;\n")
	buf.WriteString("  private tenantId?: string;\n")
	buf.WriteString("  private customHeaders: Record<string, string>;\n\n")

	buf.WriteString("  constructor(options: ClientOptions = {}) {\n")
	buf.WriteString(fmt.Sprintf("    this.baseUrl = options.baseUrl || '%s';\n", baseURL))
	buf.WriteString("    this.accessToken = options.accessToken;\n")
	buf.WriteString("    this.tenantId = options.tenantId;\n")
	buf.WriteString("    this.customHeaders = options.customHeaders || {};\n")
	buf.WriteString("  }\n\n")

	buf.WriteString("  private async request<T>(method: string, path: string, body?: any, query?: Record<string, any>): Promise<T> {\n")
	buf.WriteString("    const url = new URL(this.baseUrl + path);\n")
	buf.WriteString("    if (query) {\n")
	buf.WriteString("      Object.entries(query).forEach(([k, v]) => {\n")
	buf.WriteString("        if (v !== undefined && v !== null) url.searchParams.set(k, String(v));\n")
	buf.WriteString("      });\n")
	buf.WriteString("    }\n")
	buf.WriteString("    const headers: Record<string, string> = {\n")
	buf.WriteString("      'Content-Type': 'application/json',\n")
	buf.WriteString("      ...this.customHeaders,\n")
	buf.WriteString("    };\n")
	buf.WriteString("    if (this.accessToken) headers['Authorization'] = `Bearer ${this.accessToken}`;\n")
	buf.WriteString("    if (this.tenantId) headers['X-Tenant-ID'] = this.tenantId;\n\n")
	buf.WriteString("    const res = await fetch(url.toString(), {\n")
	buf.WriteString("      method,\n")
	buf.WriteString("      headers,\n")
	buf.WriteString("      body: body ? JSON.stringify(body) : undefined,\n")
	buf.WriteString("    });\n")
	buf.WriteString("    if (!res.ok) {\n")
	buf.WriteString("      const errorText = await res.text();\n")
	buf.WriteString("      throw new Error(`API Error [${res.status}]: ${errorText}`);\n")
	buf.WriteString("    }\n")
	buf.WriteString("    return res.json();\n")
	buf.WriteString("  }\n\n")

	// Iterate endpoints
	if paths, ok := spec["paths"].(map[string]any); ok {
		for p, item := range paths {
			if pathItem, ok := item.(map[string]any); ok {
				for method, opVal := range pathItem {
					mLower := strings.ToLower(method)
					if mLower != "get" && mLower != "post" && mLower != "put" && mLower != "delete" && mLower != "patch" {
						continue
					}
					op, _ := opVal.(map[string]any)
					methodName := generateMethodName(mLower, p, op)
					summary := ""
					if s, ok := op["summary"].(string); ok {
						summary = s
					}

					buf.WriteString(fmt.Sprintf("  /**\n   * %s %s - %s\n   */\n", strings.ToUpper(mLower), p, summary))
					buf.WriteString(fmt.Sprintf("  public async %s(body?: any, query?: Record<string, any>): Promise<any> {\n", methodName))
					buf.WriteString(fmt.Sprintf("    return this.request('%s', '%s', body, query);\n", strings.ToUpper(mLower), p))
					buf.WriteString("  }\n\n")
				}
			}
		}
	}

	buf.WriteString("}\n")
	return buf.String(), "client.ts", nil
}

func generateGoSDK(spec map[string]any, title, baseURL string) (string, string, error) {
	var buf bytes.Buffer
	buf.WriteString("package client\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\t\"time\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(fmt.Sprintf("// %s provides a Go client for accessing the API.\n", title))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", title))
	buf.WriteString("\tBaseURL     string\n")
	buf.WriteString("\tAccessToken string\n")
	buf.WriteString("\tTenantID    string\n")
	buf.WriteString("\tHTTPClient  *http.Client\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("// New%s creates a new API client instance.\n", title))
	buf.WriteString(fmt.Sprintf("func New%s(baseURL, accessToken string) *%s {\n", title, title))
	buf.WriteString(fmt.Sprintf("\tif baseURL == \"\" {\n\t\tbaseURL = \"%s\"\n\t}\n", baseURL))
	buf.WriteString(fmt.Sprintf("\treturn &%s{\n", title))
	buf.WriteString("\t\tBaseURL:     baseURL,\n")
	buf.WriteString("\t\tAccessToken: accessToken,\n")
	buf.WriteString("\t\tHTTPClient:  &http.Client{Timeout: 30 * time.Second},\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("func (c *%s) do(ctx context.Context, method, path string, body any, out any) error {\n", title))
	buf.WriteString("\tvar r io.Reader\n")
	buf.WriteString("\tif body != nil {\n")
	buf.WriteString("\t\tb, err := json.Marshal(body)\n")
	buf.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	buf.WriteString("\t\tr = bytes.NewReader(b)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treq, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, r)\n")
	buf.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	buf.WriteString("\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	buf.WriteString("\tif c.AccessToken != \"\" {\n\t\treq.Header.Set(\"Authorization\", \"Bearer \"+c.AccessToken)\n\t}\n")
	buf.WriteString("\tif c.TenantID != \"\" {\n\t\treq.Header.Set(\"X-Tenant-ID\", c.TenantID)\n\t}\n")
	buf.WriteString("\tresp, err := c.HTTPClient.Do(req)\n")
	buf.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n")
	buf.WriteString("\tif resp.StatusCode >= 400 {\n")
	buf.WriteString("\t\tb, _ := io.ReadAll(resp.Body)\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"api error status %d: %s\", resp.StatusCode, string(b))\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif out != nil {\n")
	buf.WriteString("\t\treturn json.NewDecoder(resp.Body).Decode(out)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	if paths, ok := spec["paths"].(map[string]any); ok {
		for p, item := range paths {
			if pathItem, ok := item.(map[string]any); ok {
				for method, opVal := range pathItem {
					mLower := strings.ToLower(method)
					if mLower != "get" && mLower != "post" && mLower != "put" && mLower != "delete" && mLower != "patch" {
						continue
					}
					op, _ := opVal.(map[string]any)
					methodName := strings.Title(generateMethodName(mLower, p, op))

					buf.WriteString(fmt.Sprintf("// %s calls %s %s\n", methodName, strings.ToUpper(mLower), p))
					buf.WriteString(fmt.Sprintf("func (c *%s) %s(ctx context.Context, reqBody any, respOut any) error {\n", title, methodName))
					buf.WriteString(fmt.Sprintf("\treturn c.do(ctx, \"%s\", \"%s\", reqBody, respOut)\n", strings.ToUpper(mLower), p))
					buf.WriteString("}\n\n")
				}
			}
		}
	}

	return buf.String(), "client.go", nil
}

func generatePythonSDK(spec map[string]any, title, baseURL string) (string, string, error) {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("\"\"\"\nAuto-generated Python SDK for %s\nGenerated by go-apidocs SDK Engine\n\"\"\"\n\n", title))
	buf.WriteString("import requests\n")
	buf.WriteString("from typing import Any, Dict, Optional\n\n")

	buf.WriteString(fmt.Sprintf("class %s:\n", title))
	buf.WriteString("    def __init__(self, base_url: str = None, access_token: str = None, tenant_id: str = None):\n")
	buf.WriteString(fmt.Sprintf("        self.base_url = (base_url or \"%s\").rstrip('/')\n", baseURL))
	buf.WriteString("        self.access_token = access_token\n")
	buf.WriteString("        self.tenant_id = tenant_id\n")
	buf.WriteString("        self.session = requests.Session()\n\n")

	buf.WriteString("    def _request(self, method: str, path: str, json: Any = None, params: Dict[str, Any] = None) -> Any:\n")
	buf.WriteString("        headers = {'Content-Type': 'application/json'}\n")
	buf.WriteString("        if self.access_token:\n")
	buf.WriteString("            headers['Authorization'] = f'Bearer {self.access_token}'\n")
	buf.WriteString("        if self.tenant_id:\n")
	buf.WriteString("            headers['X-Tenant-ID'] = self.tenant_id\n\n")
	buf.WriteString("        url = f\"{self.base_url}{path}\"\n")
	buf.WriteString("        resp = self.session.request(method, url, json=json, params=params, headers=headers)\n")
	buf.WriteString("        resp.raise_for_status()\n")
	buf.WriteString("        try:\n")
	buf.WriteString("            return resp.json()\n")
	buf.WriteString("        except Exception:\n")
	buf.WriteString("            return resp.text\n\n")

	if paths, ok := spec["paths"].(map[string]any); ok {
		for p, item := range paths {
			if pathItem, ok := item.(map[string]any); ok {
				for method, opVal := range pathItem {
					mLower := strings.ToLower(method)
					if mLower != "get" && mLower != "post" && mLower != "put" && mLower != "delete" && mLower != "patch" {
						continue
					}
					op, _ := opVal.(map[string]any)
					methodName := toSnakeCase(generateMethodName(mLower, p, op))

					buf.WriteString(fmt.Sprintf("    def %s(self, json: Optional[Any] = None, params: Optional[Dict[str, Any]] = None) -> Any:\n", methodName))
					buf.WriteString(fmt.Sprintf("        \"\"\"%s %s\"\"\"\n", strings.ToUpper(mLower), p))
					buf.WriteString(fmt.Sprintf("        return self._request('%s', '%s', json=json, params=params)\n\n", strings.ToUpper(mLower), p))
				}
			}
		}
	}

	return buf.String(), "client.py", nil
}

func generateMethodName(method, path string, op map[string]any) string {
	if op != nil {
		if opID, ok := op["operationId"].(string); ok && opID != "" {
			return sanitizeIdentifier(opID)
		}
	}

	clean := strings.ReplaceAll(path, "/", "_")
	clean = strings.ReplaceAll(clean, "{", "")
	clean = strings.ReplaceAll(clean, "}", "")
	clean = strings.ReplaceAll(clean, "-", "_")
	clean = strings.Trim(clean, "_")

	parts := strings.Split(clean, "_")
	var camelParts []string
	for i, part := range parts {
		if part == "" {
			continue
		}
		if i == 0 {
			camelParts = append(camelParts, strings.ToLower(part))
		} else {
			camelParts = append(camelParts, strings.Title(strings.ToLower(part)))
		}
	}

	return strings.ToLower(method) + strings.Title(strings.Join(camelParts, ""))
}

func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteRune('_')
			}
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
